sudo: false
language: node_js
addons:
  firefox: latest
  chrome: stable
before_script:
- npm install -g bower polymer-cli
- bower install
script:
- npm test
- polymer test
before_deploy:
- npm install -g vulcanize
- ./build.sh
- ./build-gem.sh
deploy:
  provider: rubygems
  skip_cleanup: true
  api_key:
    secure: WFNP2JWq5eF6fTThLymLrqvjB7NaWGXKEOVgy+dtbTsMCGFCgVpHA62qPOOeFe84ZJeoVZbqrPLsy6ud9CbEw6g94dgacj9xD5AN5LZTQzDQmnxZ156n6jyXMKt6yqf0zs+DqLr1t7wPcODHmaY8+49RZJx5xrSp+kzMQxlE4eYMj99OmOCB/w2vrqGO24JYXTnBlGfv/vwUXKpB5bC9853hk+Q1yn/ojt/IHTTouPRDDVBWb1HfUC6mBM3FrK/7DwBKEFP62pIgEvp+qnLc3u/EVsaM6rMbjKz484MdrFYHCWO0SWleDZohYkinRFoM/sz5ur3gaBrXuj2q92jpfbYq+Qkdh6WwmCHv6VMMddJuaBu1z0bMtHzjUpGc9LmX5NAXCw4aFHMyV0CeYTXo6OhiOiurBb2aoxFOrna+0/iJ5VU7k7agUPZldFy5BuSiqQh2G4lWjuq5ZbKw0dMtsfONGHerNr8ph3WNEmJSWuZF4h5y5CBKJ1bqbiuWkpA+Yi/+kiZq2r+Lfa6K/7tBZy+mOudUxkXyNHNF+Jxvn4Rrfqc0aDVQjIcF2LajnDcZ6L4mVKt9VofOsVj3rpbxyn4e5KnIXr19a7XPSaTvvBTUor9FbL7kPenaV6e5q2u88eOJLalR1K4UMhFKdBhpbCMHFZFHFOqN3qQnNFFxPVI=
  gem: mumuki-gobstones-blockly
  on:
    tags: true
    repo: mumuki/gs-element-blockly
